---
name: Wilderness
main: muqsit\wilderness\Wilderness
api: 3.0.0
mcpe-protocol: 422
version: 1
author: musqit, princepines
commands:
  wilderness:
    aliases:
    - wild
    permission: wilderness.command
permissions:
  wilderness:
    default: true
    childrern:
      wilderness.command:
        default: true
...
